name: Update Submodules

permissions:
  contents: write  # 允许写入内容
  issues: read     # 允许读取问题

on:
  push:
    branches:
      - master  # 改为主分支名称

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # 检出子模块

      - name: Set up Git user
        run: |
          git config --global user.email "NWMA_FYWF@Hotmail.com"
          git config --global user.name "NWMA-FYWF"

      - name: Update submodules
        run: |
          git submodule update --remote
          cd themes/PaperMod  # 进入子模块目录
          git fetch origin  # 获取远程更新
          git merge origin/master --allow-unrelated-histories  # 合并不相关的历史
          cd ../..  # 返回主目录
          git add .
          git commit -m "Updated submodule with unrelated histories" || echo "No changes to commit"
          git push origin master  # 推送到主分支

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NWMA-FYWF/Blog.git 
main

