name: Update Submodules

on:
  push:
    branches:
      - master  # 改为主分支名称

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # 检出子模块

      - name: Update submodules
        run: |
          git submodule update --remote
          cd themes/PaperMod  # 进入子模块目录
          git fetch origin  # 获取远程更新
          git merge origin/master --allow-unrelated-histories  # 合并不相关的历史
          cd ../..  # 返回主目录
          git add .
          git commit -m "Updated submodule with unrelated histories" || echo "No changes to commit"
          git push origin master  # 推送到主分支
